/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/cart/index" |
       "/pages/index/demo" |
       "/pages/mine/index" |
       "/pages/mine/vip-center" |
       "/pages/order/index" |
       "/pages/product/exchange" |
       "/pages/product/invite-friends" |
       "/pages/product/list" |
       "/pages/product/photo-price" |
       "/pages/product/recycle-list-webview" |
       "/pages/product/warranty-query";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/order/index" | "/pages/cart/index" | "/pages/mine/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
